# 项目相关配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /salary
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30

# 日志配置
logging:
  level:
    root: info
    com.salary.dao: debug
    org.springframework: warn

# Spring配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  # 模板引擎
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: utf-8
    check-template-location: true
    check-template: true
    prefix: classpath:/templates/
    suffix: .html
  #json
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置数据源文件application-dev.yml
  profiles: 
    active: dev

  # 缓存配置
  cache:
    type: redis
    redis:
      #是否缓存空值,防止缓存穿透
      cache-null-values: true
      #缓存过期时间（单位为毫秒）
      time-to-live: 100000
      #缓存前缀，用于区分其他缓存,不指定前缀，默认使用缓存的名字作为前缀
      #      key-prefix: CACHE_
      #是否使用缓存前缀，false不使用任何缓存前缀
      #      use-key-prefix: false

  # redis单机版配置
  redis:
    # 操作第几个库
    database: 1
    # redis路径
    host: localhost
    # 端口
    port: 6379
    # 密码
    password:
    # 连接超时时间（毫秒）
    timeout : 300
    client-type: lettuce
    #连接池
    lettuce:
      pool:
        # 最大连接个数
        max-active: 10
        # 等待时间
        max-wait: 3000ms
        # 最大空闲
        max-idle: 8
        # 初始化最小
        min-idle: 5

# MyBatis
mybatis:
    # 搜索指定包别名
    type-aliases-package: com.salary.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapper-locations: classpath:mapper/*xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql